#
# Module manifest for module 'ShieldedVMTemplate'
#
# Generated by: Microsoft Corporation
#
# Generated on: 12/08/2014
#

@{

# Script module or binary module file associated with this manifest.
NestedModules = 'Microsoft.Windows.HardenedFabric.Cmdlets'

# This GUID is used to uniquely identify this module.
GUID = 'AFB7D213-3F7E-4A0D-86EB-02D57AD7B858'

# The author of this module.
Author = 'Microsoft Corporation'

# The company or vendor for this module.
CompanyName = 'Microsoft Corporation'

# The copyright statement for this module.
Copyright = '© Microsoft Corporation. All rights reserved.'

# The version of this module.
ModuleVersion = '1.0.0.0'

# The minimum version of PowerShell needed to use this module.
PowerShellVersion = '5.1'

# The CLR version required to use this module.
CLRVersion = '4.0'

# Cmdlets to export from this module
CmdletsToExport = "Protect-TemplateDisk", "Initialize-VMShieldingHelperVHD"

# Help Info Uri
HelpInfoUri='https://go.microsoft.com/fwlink/?LinkID=524080'

CompatiblePSEditions = @('Desktop', 'Core')
}
